server:
  port: 8888
logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.module
  mapper-locations:
    - mapper/*
